# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guestcc/share/ccnet-log/ccnet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guestcc/share/ccnet-log/ccnet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guestcc/share/ccnet-log/ccnet/CMakeFiles /home/guestcc/share/ccnet-log/ccnet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guestcc/share/ccnet-log/ccnet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AsyncLog_test

# Build rule for target.
AsyncLog_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AsyncLog_test
.PHONY : AsyncLog_test

# fast build rule for target.
AsyncLog_test/fast:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/build
.PHONY : AsyncLog_test/fast

#=============================================================================
# Target rules for targets named ccnet

# Build rule for target.
ccnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ccnet
.PHONY : ccnet

# fast build rule for target.
ccnet/fast:
	$(MAKE) -f CMakeFiles/ccnet.dir/build.make CMakeFiles/ccnet.dir/build
.PHONY : ccnet/fast

src/base/Logger.o: src/base/Logger.cpp.o

.PHONY : src/base/Logger.o

# target to build an object file
src/base/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/base/Logger.cpp.o
.PHONY : src/base/Logger.cpp.o

src/base/Logger.i: src/base/Logger.cpp.i

.PHONY : src/base/Logger.i

# target to preprocess a source file
src/base/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/base/Logger.cpp.i
.PHONY : src/base/Logger.cpp.i

src/base/Logger.s: src/base/Logger.cpp.s

.PHONY : src/base/Logger.s

# target to generate assembly for a file
src/base/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/base/Logger.cpp.s
.PHONY : src/base/Logger.cpp.s

src/base/Threadpool.o: src/base/Threadpool.cpp.o

.PHONY : src/base/Threadpool.o

# target to build an object file
src/base/Threadpool.cpp.o:
	$(MAKE) -f CMakeFiles/ccnet.dir/build.make CMakeFiles/ccnet.dir/src/base/Threadpool.cpp.o
.PHONY : src/base/Threadpool.cpp.o

src/base/Threadpool.i: src/base/Threadpool.cpp.i

.PHONY : src/base/Threadpool.i

# target to preprocess a source file
src/base/Threadpool.cpp.i:
	$(MAKE) -f CMakeFiles/ccnet.dir/build.make CMakeFiles/ccnet.dir/src/base/Threadpool.cpp.i
.PHONY : src/base/Threadpool.cpp.i

src/base/Threadpool.s: src/base/Threadpool.cpp.s

.PHONY : src/base/Threadpool.s

# target to generate assembly for a file
src/base/Threadpool.cpp.s:
	$(MAKE) -f CMakeFiles/ccnet.dir/build.make CMakeFiles/ccnet.dir/src/base/Threadpool.cpp.s
.PHONY : src/base/Threadpool.cpp.s

src/base/Timestamp.o: src/base/Timestamp.cpp.o

.PHONY : src/base/Timestamp.o

# target to build an object file
src/base/Timestamp.cpp.o:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/base/Timestamp.cpp.o
.PHONY : src/base/Timestamp.cpp.o

src/base/Timestamp.i: src/base/Timestamp.cpp.i

.PHONY : src/base/Timestamp.i

# target to preprocess a source file
src/base/Timestamp.cpp.i:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/base/Timestamp.cpp.i
.PHONY : src/base/Timestamp.cpp.i

src/base/Timestamp.s: src/base/Timestamp.cpp.s

.PHONY : src/base/Timestamp.s

# target to generate assembly for a file
src/base/Timestamp.cpp.s:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/base/Timestamp.cpp.s
.PHONY : src/base/Timestamp.cpp.s

src/test/AsyncLog_test.o: src/test/AsyncLog_test.cpp.o

.PHONY : src/test/AsyncLog_test.o

# target to build an object file
src/test/AsyncLog_test.cpp.o:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/test/AsyncLog_test.cpp.o
.PHONY : src/test/AsyncLog_test.cpp.o

src/test/AsyncLog_test.i: src/test/AsyncLog_test.cpp.i

.PHONY : src/test/AsyncLog_test.i

# target to preprocess a source file
src/test/AsyncLog_test.cpp.i:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/test/AsyncLog_test.cpp.i
.PHONY : src/test/AsyncLog_test.cpp.i

src/test/AsyncLog_test.s: src/test/AsyncLog_test.cpp.s

.PHONY : src/test/AsyncLog_test.s

# target to generate assembly for a file
src/test/AsyncLog_test.cpp.s:
	$(MAKE) -f CMakeFiles/AsyncLog_test.dir/build.make CMakeFiles/AsyncLog_test.dir/src/test/AsyncLog_test.cpp.s
.PHONY : src/test/AsyncLog_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... AsyncLog_test"
	@echo "... rebuild_cache"
	@echo "... ccnet"
	@echo "... src/base/Logger.o"
	@echo "... src/base/Logger.i"
	@echo "... src/base/Logger.s"
	@echo "... src/base/Threadpool.o"
	@echo "... src/base/Threadpool.i"
	@echo "... src/base/Threadpool.s"
	@echo "... src/base/Timestamp.o"
	@echo "... src/base/Timestamp.i"
	@echo "... src/base/Timestamp.s"
	@echo "... src/test/AsyncLog_test.o"
	@echo "... src/test/AsyncLog_test.i"
	@echo "... src/test/AsyncLog_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

